### ISSUE TITLE
Self disconnect after N minutes

### ISSUE THREAD

**Issue by DLi7077** [Juke-Duke/JukeBox#6]
bot should leave the discord call after (20) minutes of inactivity so this doesn't happen:
![image](https://user-images.githubusercontent.com/51217000/210276557-9d1502e2-dd2b-418a-a49a-00a22f17a0fa.png)

**Comment by DLi7077** [comment]
proposed changes: https://docs.google.com/document/d/1UX_eNpZeZ0GY1nMBUvLCo9qxWxdeURcvs029mT_odoo/edit?usp=sharing

**Comment by DLi7077** [comment]
or just use this lmao
https://github.com/angelobreuer/Lavalink4NET/wiki/Inactivity-Tracking#example-options

**Comment by Juke-Duke** [comment]
This has been implemented. Thank you @DLi7077 .
